# Generated by Django 4.2.7 on 2023-11-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0002_player_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.DeleteModel(
            name='manager_Db',
        ),
    ]
