# Generated by Django 4.2.7 on 2023-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0003_category_db_delete_manager_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, verbose_name=False)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
