# Generated by Django 4.2.7 on 2023-12-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0004_product_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='player_Db',
        ),
    ]
